version: 2.1

jobs:
  workspace-job:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Create File
          command: |
            echo "This file is created inside CircleCI workspace" > sample.txt

      - run:
          name: Show File Content
          command: |
            echo "Displaying file:"
            cat sample.txt

      - run:
          name: List Workspace Files
          command: ls -la

workflows:
  version: 2
  workspace-workflow:
    jobs:
      - workspace-job
