version: 2.1

parameters:
  username:
    type: string
    default: "Student"

jobs:
  param-job:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Print Parameter
          command: echo "Hello Tejaswi"

workflows:
  version: 2
  param-workflow:
    jobs:
      - param-job
