version: 2.1

jobs:
  mini-ci:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Show Files
          command: ls -la

      - run:
          name: Compile Java
          command: javac Hello.java

      - run:
          name: Run Java
          command: java Hello

      - store_artifacts:
          path: Hello.class
          destination: compiled-output

workflows:
  version: 2
  mini-ci-workflow:
    jobs:
      - mini-ci
