version: 2.1

jobs:
  post-job:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Compile Java
          command: javac Hello.java

      - run:
          name: Run Java
          command: java Hello

      # Success Message
      - run:
          name: Success Message
          command: echo "BUILD SUCCESSFUL"
          when: on_success

      # Failure Message
      - run:
          name: Failure Message
          command: echo "BUILD FAILED"
          when: on_fail

workflows:
  version: 2
  post-workflow:
    jobs:
      - post-job
